markdown: kramdown
highlighter: pygments
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

#gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: UA-68588325-3

#repository: https://github.com/jekyll/jekyll
#help_url: https://github.com/jekyll/jekyll-help

collections:
  docs:
    output: true

name: Gala • Simple integration of your Mac
description: Connect your Mac to Windows AD, SSO and SMB shares
url: http://shufflepuck.github.io
baseurl: /Gala
repository: http://github.com/shufflepuck/gala

gems:
  - jekyll-feed
